pipeline {
    agent any
    stages {
        stage('Submit Stack') {
            steps {
            sh "aws cloudformation create-stack --stack-name s3bucket --template-body file://cloudformation/s3-cft.yaml --region 'us-east-1'"
              }
             }
            }
            }